version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/file_storage
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0606

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: file_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0606
    ports:
      - "5432:5432"
